name: librus_go
description: An unofficial Librus Synergia mobile app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  rxdart: ^0.22.2
  shared_preferences: ^0.5.3+4
  cookie_jar: ^1.0.1
  html: ^0.14.0+2
  dio: ^2.1.16
  connectivity: ^0.4.4
  table_calendar: ^2.0.1
  intl: ^0.15.7
  url_launcher: ^5.1.3
  firebase_analytics: ^5.0.2
  scroll_to_index: ^1.0.2
  charts_flutter: ^0.8.1
  local_auth: ^0.6.0+1
  preferences: ^5.0.2
  sentry: ">=2.0.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png